<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'App__Entity__Matchy__CLASSMETADATA__' => 0,
'App__Entity__Team__CLASSMETADATA__' => 1,
'App__Entity__CoachingSession__CLASSMETADATA__' => 2,
'App__Entity__TrainingPlan__CLASSMETADATA__' => 3,

], [

0 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Matchy',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\MatchyRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'game' => $o[2],
                        'match_date' => $o[3],
                        'score_team1' => $o[4],
                        'score_team2' => $o[5],
                        'status' => $o[6],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'game' => 'game',
                        'match_date' => 'match_date',
                        'score_team1' => 'score_team1',
                        'score_team2' => 'score_team2',
                        'status' => 'status',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'game' => 'game',
                        'match_date' => 'match_date',
                        'score_team1' => 'score_team1',
                        'score_team2' => 'score_team2',
                        'status' => 'status',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'matchy',
                    ],
                ],
                'associationMappings' => [
                    [
                        'team1' => $o[7],
                        'team2' => $o[9],
                        'winner_team' => $o[11],
                    ],
                ],
                'idGenerator' => [
                    $o[13],
                ],
                'name' => [
                    'App\\Entity\\Matchy',
                    8 => 'team1_id',
                    10 => 'team2_id',
                    12 => 'winner_team_id',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'datetime',
                    'integer',
                    'integer',
                    'string',
                ],
                'fieldName' => [
                    1 => 'id',
                    'game',
                    'match_date',
                    'score_team1',
                    'score_team2',
                    'status',
                ],
                'columnName' => [
                    1 => 'id',
                    'game',
                    'match_date',
                    'score_team1',
                    'score_team2',
                    'status',
                ],
                'length' => [
                    2 => 255,
                    6 => 50,
                ],
                'nullable' => [
                    4 => true,
                    true,
                    8 => false,
                    10 => false,
                    12 => true,
                ],
                'fetch' => [
                    7 => 2,
                    9 => 2,
                    11 => 2,
                ],
                'sourceEntity' => [
                    7 => 'App\\Entity\\Matchy',
                    9 => 'App\\Entity\\Matchy',
                    11 => 'App\\Entity\\Matchy',
                ],
                'inversedBy' => [
                    7 => 'matchesAsTeam1',
                    9 => 'matchesAsTeam2',
                    11 => 'matchesWon',
                ],
                'sourceToTargetKeyColumns' => [
                    7 => [
                        'team1_id' => 'id',
                    ],
                    9 => [
                        'team2_id' => 'id',
                    ],
                    11 => [
                        'winner_team_id' => 'id',
                    ],
                ],
                'targetToSourceKeyColumns' => [
                    7 => [
                        'id' => 'team1_id',
                    ],
                    9 => [
                        'id' => 'team2_id',
                    ],
                    11 => [
                        'id' => 'winner_team_id',
                    ],
                ],
                'joinColumns' => [
                    7 => [
                        $o[8],
                    ],
                    9 => [
                        $o[10],
                    ],
                    11 => [
                        $o[12],
                    ],
                ],
                'joinColumnFieldNames' => [
                    7 => [
                        'team1_id' => 'team1_id',
                    ],
                    9 => [
                        'team2_id' => 'team2_id',
                    ],
                    11 => [
                        'winner_team_id' => 'winner_team_id',
                    ],
                ],
                'deferrable' => [
                    8 => false,
                    10 => false,
                ],
                'unique' => [
                    8 => false,
                    10 => false,
                ],
                'referencedColumnName' => [
                    8 => 'id',
                    10 => 'id',
                    12 => 'id',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    7 => 'team1',
                    9 => 'team2',
                    11 => 'winner_team',
                ],
                'targetEntity' => [
                    7 => 'App\\Entity\\Team',
                    9 => 'App\\Entity\\Team',
                    11 => 'App\\Entity\\Team',
                ],
            ],
        ],
        $o[0],
        []
    );
},
1 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'],
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\Team',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\TeamRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'name' => $o[2],
                        'game' => $o[3],
                        'creation_date' => $o[4],
                        'coach_id' => $o[5],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'name' => 'name',
                        'game' => 'game',
                        'creation_date' => 'creation_date',
                        'coach_id' => 'coach_id',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'name' => 'name',
                        'game' => 'game',
                        'creation_date' => 'creation_date',
                        'coach_id' => 'coach_id',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'team',
                    ],
                ],
                'associationMappings' => [
                    [
                        'matchesAsTeam1' => $o[6],
                        'matchesAsTeam2' => $o[7],
                        'matchesWon' => $o[8],
                    ],
                ],
                'idGenerator' => [
                    $o[9],
                ],
                'name' => [
                    'App\\Entity\\Team',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'string',
                    'datetime',
                    'integer',
                ],
                'fieldName' => [
                    1 => 'id',
                    'name',
                    'game',
                    'creation_date',
                    'coach_id',
                ],
                'columnName' => [
                    1 => 'id',
                    'name',
                    'game',
                    'creation_date',
                    'coach_id',
                ],
                'length' => [
                    2 => 255,
                    255,
                ],
                'fetch' => [
                    6 => 2,
                    2,
                    2,
                ],
                'sourceEntity' => [
                    6 => 'App\\Entity\\Team',
                    'App\\Entity\\Team',
                    'App\\Entity\\Team',
                ],
                'mappedBy' => [
                    6 => 'team1',
                    'team2',
                    'winner_team',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    6 => 'matchesAsTeam1',
                    'matchesAsTeam2',
                    'matchesWon',
                ],
                'targetEntity' => [
                    6 => 'App\\Entity\\Matchy',
                    'App\\Entity\\Matchy',
                    'App\\Entity\\Matchy',
                ],
            ],
        ],
        $o[0],
        []
    );
},
2 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
            clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\CoachingSession',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\CoachingSessionRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'coach_id' => $o[2],
                        'team_id' => $o[3],
                        'session_date' => $o[4],
                        'duration' => $o[5],
                        'notes' => $o[6],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'coach_id' => 'coach_id',
                        'team_id' => 'team_id',
                        'session_date' => 'session_date',
                        'duration' => 'duration',
                        'notes' => 'notes',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'coach_id' => 'coach_id',
                        'team_id' => 'team_id',
                        'session_date' => 'session_date',
                        'duration' => 'duration',
                        'notes' => 'notes',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'coaching_session',
                    ],
                ],
                'associationMappings' => [
                    [
                        'training_plan' => $o[7],
                    ],
                ],
                'idGenerator' => [
                    $o[9],
                ],
                'name' => [
                    'App\\Entity\\CoachingSession',
                    8 => 'training_plan_id',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'integer',
                    'integer',
                    'datetime',
                    'integer',
                    'string',
                ],
                'fieldName' => [
                    1 => 'id',
                    'coach_id',
                    'team_id',
                    'session_date',
                    'duration',
                    'notes',
                ],
                'columnName' => [
                    1 => 'id',
                    'coach_id',
                    'team_id',
                    'session_date',
                    'duration',
                    'notes',
                ],
                'length' => [
                    6 => 255,
                ],
                'nullable' => [
                    6 => true,
                    8 => false,
                ],
                'fetch' => [
                    7 => 2,
                ],
                'sourceEntity' => [
                    7 => 'App\\Entity\\CoachingSession',
                ],
                'inversedBy' => [
                    7 => 'coachingSessions',
                ],
                'sourceToTargetKeyColumns' => [
                    7 => [
                        'training_plan_id' => 'id',
                    ],
                ],
                'targetToSourceKeyColumns' => [
                    7 => [
                        'id' => 'training_plan_id',
                    ],
                ],
                'joinColumns' => [
                    7 => [
                        $o[8],
                    ],
                ],
                'joinColumnFieldNames' => [
                    7 => [
                        'training_plan_id' => 'training_plan_id',
                    ],
                ],
                'deferrable' => [
                    8 => false,
                ],
                'unique' => [
                    8 => false,
                ],
                'referencedColumnName' => [
                    8 => 'id',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    7 => 'training_plan',
                ],
                'targetEntity' => [
                    7 => 'App\\Entity\\TrainingPlan',
                ],
            ],
        ],
        $o[0],
        []
    );
},
3 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
            clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
            clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
            clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
        ],
        null,
        [
            'stdClass' => [
                'namespace' => [
                    'App\\Entity',
                ],
                'rootEntityName' => [
                    'App\\Entity\\TrainingPlan',
                ],
                'customRepositoryClassName' => [
                    'App\\Repository\\TrainingPlanRepository',
                ],
                'identifier' => [
                    [
                        'id',
                    ],
                ],
                'generatorType' => [
                    4,
                ],
                'fieldMappings' => [
                    [
                        'id' => $o[1],
                        'title' => $o[2],
                        'description' => $o[3],
                        'focus_area' => $o[4],
                        'difficulty_level' => $o[5],
                        'coach_id' => $o[6],
                        'created_at' => $o[7],
                    ],
                ],
                'fieldNames' => [
                    [
                        'id' => 'id',
                        'title' => 'title',
                        'description' => 'description',
                        'focus_area' => 'focus_area',
                        'difficulty_level' => 'difficulty_level',
                        'coach_id' => 'coach_id',
                        'created_at' => 'created_at',
                    ],
                ],
                'columnNames' => [
                    [
                        'id' => 'id',
                        'title' => 'title',
                        'description' => 'description',
                        'focus_area' => 'focus_area',
                        'difficulty_level' => 'difficulty_level',
                        'coach_id' => 'coach_id',
                        'created_at' => 'created_at',
                    ],
                ],
                'table' => [
                    [
                        'name' => 'training_plan',
                    ],
                ],
                'associationMappings' => [
                    [
                        'coachingSessions' => $o[8],
                    ],
                ],
                'idGenerator' => [
                    $o[9],
                ],
                'name' => [
                    'App\\Entity\\TrainingPlan',
                ],
                'id' => [
                    1 => true,
                ],
                'type' => [
                    1 => 'integer',
                    'string',
                    'string',
                    'string',
                    'string',
                    'integer',
                    'datetime_immutable',
                ],
                'fieldName' => [
                    1 => 'id',
                    'title',
                    'description',
                    'focus_area',
                    'difficulty_level',
                    'coach_id',
                    'created_at',
                ],
                'columnName' => [
                    1 => 'id',
                    'title',
                    'description',
                    'focus_area',
                    'difficulty_level',
                    'coach_id',
                    'created_at',
                ],
                'length' => [
                    2 => 255,
                    255,
                    255,
                    255,
                ],
                'fetch' => [
                    8 => 2,
                ],
                'sourceEntity' => [
                    8 => 'App\\Entity\\TrainingPlan',
                ],
                'mappedBy' => [
                    8 => 'training_plan',
                ],
            ],
            'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
                'fieldName' => [
                    8 => 'coachingSessions',
                ],
                'targetEntity' => [
                    8 => 'App\\Entity\\CoachingSession',
                ],
            ],
        ],
        $o[0],
        []
    );
},

]];
