<?php

namespace ContainerIAL3q0d;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LZlyEWVService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.LZlyEWV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LZlyEWV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'trainingPlan' => ['privates', '.errored..service_locator.LZlyEWV.App\\Entity\\TrainingPlan', NULL, 'Cannot autowire service ".service_locator.LZlyEWV": it needs an instance of "App\\Entity\\TrainingPlan" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'trainingPlan' => 'App\\Entity\\TrainingPlan',
        ]);
    }
}
