<?php

namespace ContainerIAL3q0d;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCoachingSessionRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\CoachingSessionRepository' shared autowired service.
     *
     * @return \App\Repository\CoachingSessionRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\CoachingSessionRepository'] = new \App\Repository\CoachingSessionRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
