<?php

namespace ContainerIAL3q0d;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCoachingSessionControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\CoachingSessionController' shared autowired service.
     *
     * @return \App\Controller\CoachingSessionController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\CoachingSessionController'] = $instance = new \App\Controller\CoachingSessionController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\CoachingSessionController', $container));

        return $instance;
    }
}
