<?php

namespace ContainerIAL3q0d;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMatchyControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Back\MatchyController' shared autowired service.
     *
     * @return \App\Controller\Back\MatchyController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Back\\MatchyController'] = $instance = new \App\Controller\Back\MatchyController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Back\\MatchyController', $container));

        return $instance;
    }
}
