<?php

namespace ContainerIAL3q0d;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTrainingPlanRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\TrainingPlanRepository' shared autowired service.
     *
     * @return \App\Repository\TrainingPlanRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\TrainingPlanRepository'] = new \App\Repository\TrainingPlanRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
