<?php

namespace ContainerIAL3q0d;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTeamControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Back\TeamController' shared autowired service.
     *
     * @return \App\Controller\Back\TeamController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Back\\TeamController'] = $instance = new \App\Controller\Back\TeamController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Back\\TeamController', $container));

        return $instance;
    }
}
