<?php

namespace ContainerIAL3q0d;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTrainingPlanTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\TrainingPlanType' shared autowired service.
     *
     * @return \App\Form\TrainingPlanType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\TrainingPlanType'] = new \App\Form\TrainingPlanType();
    }
}
