<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CoachingSession extends \App\Entity\CoachingSession implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'coach_id' => [parent::class, 'coach_id', null],
        "\0".parent::class."\0".'duration' => [parent::class, 'duration', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'notes' => [parent::class, 'notes', null],
        "\0".parent::class."\0".'session_date' => [parent::class, 'session_date', null],
        "\0".parent::class."\0".'team_id' => [parent::class, 'team_id', null],
        "\0".parent::class."\0".'training_plan' => [parent::class, 'training_plan', null],
        'coach_id' => [parent::class, 'coach_id', null],
        'duration' => [parent::class, 'duration', null],
        'id' => [parent::class, 'id', null],
        'notes' => [parent::class, 'notes', null],
        'session_date' => [parent::class, 'session_date', null],
        'team_id' => [parent::class, 'team_id', null],
        'training_plan' => [parent::class, 'training_plan', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
