<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Team extends \App\Entity\Team implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'coach_id' => [parent::class, 'coach_id', null],
        "\0".parent::class."\0".'creation_date' => [parent::class, 'creation_date', null],
        "\0".parent::class."\0".'game' => [parent::class, 'game', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'matchesAsTeam1' => [parent::class, 'matchesAsTeam1', null],
        "\0".parent::class."\0".'matchesAsTeam2' => [parent::class, 'matchesAsTeam2', null],
        "\0".parent::class."\0".'matchesWon' => [parent::class, 'matchesWon', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        'coach_id' => [parent::class, 'coach_id', null],
        'creation_date' => [parent::class, 'creation_date', null],
        'game' => [parent::class, 'game', null],
        'id' => [parent::class, 'id', null],
        'matchesAsTeam1' => [parent::class, 'matchesAsTeam1', null],
        'matchesAsTeam2' => [parent::class, 'matchesAsTeam2', null],
        'matchesWon' => [parent::class, 'matchesWon', null],
        'name' => [parent::class, 'name', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
