<?php

namespace Container0uFQjEc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WxFNVXdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WxFNVXd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WxFNVXd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'tournament' => ['privates', '.errored..service_locator.WxFNVXd.App\\Entity\\Tournament', NULL, 'Cannot autowire service ".service_locator.WxFNVXd": it needs an instance of "App\\Entity\\Tournament" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'tournament' => 'App\\Entity\\Tournament',
        ]);
    }
}
