<?php

namespace Container0uFQjEc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AMXBPGTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aMXBPGT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aMXBPGT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'payment' => ['privates', '.errored..service_locator.aMXBPGT.App\\Entity\\Payment', NULL, 'Cannot autowire service ".service_locator.aMXBPGT": it needs an instance of "App\\Entity\\Payment" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'payment' => 'App\\Entity\\Payment',
        ]);
    }
}
