<?php

namespace Container0uFQjEc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__7uivSMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..7uivSM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..7uivSM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'shopItem' => ['privates', '.errored..service_locator..7uivSM.App\\Entity\\ShopItem', NULL, 'Cannot autowire service ".service_locator..7uivSM": it needs an instance of "App\\Entity\\ShopItem" but this type has been excluded in "config/services.yaml".'],
        ], [
            'shopItem' => 'App\\Entity\\ShopItem',
        ]);
    }
}
