<?php

namespace Container0uFQjEc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZGC8iBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zGC8i_B' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zGC8i_B'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tournament' => ['privates', '.errored..service_locator.zGC8i_B.App\\Entity\\Tournament', NULL, 'Cannot autowire service ".service_locator.zGC8i_B": it needs an instance of "App\\Entity\\Tournament" but this type has been excluded in "config/services.yaml".'],
        ], [
            'tournament' => 'App\\Entity\\Tournament',
        ]);
    }
}
