<?php

namespace Container0uFQjEc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QouIDzdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qouIDzd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qouIDzd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repRepo' => ['privates', 'App\\Repository\\ReponseQuestionnaireRepository', 'getReponseQuestionnaireRepositoryService', true],
            'repo' => ['privates', 'App\\Repository\\AgentRepository', 'getAgentRepositoryService', true],
        ], [
            'repRepo' => 'App\\Repository\\ReponseQuestionnaireRepository',
            'repo' => 'App\\Repository\\AgentRepository',
        ]);
    }
}
