<?php

namespace Container0uFQjEc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5RxUGVvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5RxUGVv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5RxUGVv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'coachingSessionRepository' => ['privates', 'App\\Repository\\CoachingSessionRepository', 'getCoachingSessionRepositoryService', true],
            'trainingPlanRepository' => ['privates', 'App\\Repository\\TrainingPlanRepository', 'getTrainingPlanRepositoryService', true],
        ], [
            'coachingSessionRepository' => 'App\\Repository\\CoachingSessionRepository',
            'trainingPlanRepository' => 'App\\Repository\\TrainingPlanRepository',
        ]);
    }
}
