<?php

namespace Container0uFQjEc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSetupUserTableCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\SetupUserTableCommand' shared autowired service.
     *
     * @return \App\Command\SetupUserTableCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'SetupUserTableCommand.php';

        $container->privates['App\\Command\\SetupUserTableCommand'] = $instance = new \App\Command\SetupUserTableCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('app:setup-user-table');
        $instance->setDescription('Creates the user table and adds dummy data');

        return $instance;
    }
}
