<?php

namespace Container0uFQjEc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTournamentRewardService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.R7y6JbM.App\Entity\TournamentReward' shared service.
     *
     * @return \App\Entity\TournamentReward
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.R7y6JbM": it needs an instance of "App\\Entity\\TournamentReward" but this type has been excluded in "config/services.yaml".');
    }
}
