<?php

namespace Container0uFQjEc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTournament2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.zGC8i_B.App\Entity\Tournament' shared service.
     *
     * @return \App\Entity\Tournament
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.zGC8i_B": it needs an instance of "App\\Entity\\Tournament" but this type has been excluded in "config/services.yaml".');
    }
}
