<?php

namespace ContainerLLdAjQf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YeG17SHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YeG17SH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YeG17SH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'shopItemRepository' => ['privates', 'App\\Repository\\ShopItemRepository', 'getShopItemRepositoryService', true],
        ], [
            'entityManager' => '?',
            'shopItemRepository' => 'App\\Repository\\ShopItemRepository',
        ]);
    }
}
