<?php

namespace ContainerLLdAjQf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RqBRMGZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RqBRMGZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RqBRMGZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'agent' => ['privates', '.errored..service_locator.RqBRMGZ.App\\Entity\\Agent', NULL, 'Cannot autowire service ".service_locator.RqBRMGZ": it needs an instance of "App\\Entity\\Agent" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'agent' => 'App\\Entity\\Agent',
            'em' => '?',
        ]);
    }
}
