<?php

namespace ContainerLLdAjQf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CdYw2xService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Cd_yw2x' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Cd_yw2x'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'matchyRepository' => ['privates', 'App\\Repository\\MatchyRepository', 'getMatchyRepositoryService', true],
        ], [
            'matchyRepository' => 'App\\Repository\\MatchyRepository',
        ]);
    }
}
