<?php

namespace ContainerLLdAjQf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HM8d51PService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hM8d51P' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hM8d51P'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'trainingPlan' => ['privates', '.errored..service_locator.hM8d51P.App\\Entity\\TrainingPlan', NULL, 'Cannot autowire service ".service_locator.hM8d51P": it needs an instance of "App\\Entity\\TrainingPlan" but this type has been excluded in "config/services.yaml".'],
        ], [
            'trainingPlan' => 'App\\Entity\\TrainingPlan',
        ]);
    }
}
