<?php

namespace ContainerLLdAjQf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAgent6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.r0EpZfZ.App\Entity\Agent' shared service.
     *
     * @return \App\Entity\Agent
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.r0EpZfZ": it needs an instance of "App\\Entity\\Agent" but this type has been excluded in "config/services.yaml".');
    }
}
