<?php

namespace ContainerLLdAjQf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCoachingSessionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.TsVqtcP.App\Entity\CoachingSession' shared service.
     *
     * @return \App\Entity\CoachingSession
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.TsVqtcP": it needs an instance of "App\\Entity\\CoachingSession" but this type has been excluded in "config/services.yaml".');
    }
}
