<?php

namespace ContainerLLdAjQf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTrainingPlanService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.LZlyEWV.App\Entity\TrainingPlan' shared service.
     *
     * @return \App\Entity\TrainingPlan
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.LZlyEWV": it needs an instance of "App\\Entity\\TrainingPlan" but this type has been excluded in "config/services.yaml".');
    }
}
