twig:
    default_path: '%kernel.project_dir%/templates'
<<<<<<< HEAD
    globals:
        
=======

>>>>>>> e2422cfde5b308b3f914dbb9a3dd46d1907df62f
when@test:
    twig:
        strict_variables: true


