<?php

namespace Container0uFQjEc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OzCmgbxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ozCmgbx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ozCmgbx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'coachingSession' => ['privates', '.errored..service_locator.ozCmgbx.App\\Entity\\CoachingSession', NULL, 'Cannot autowire service ".service_locator.ozCmgbx": it needs an instance of "App\\Entity\\CoachingSession" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'coachingSession' => 'App\\Entity\\CoachingSession',
            'entityManager' => '?',
        ]);
    }
}
