<?php

namespace Container0uFQjEc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VJJ7DQyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vJJ7DQy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vJJ7DQy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'matchy' => ['privates', '.errored..service_locator.vJJ7DQy.App\\Entity\\Matchy', NULL, 'Cannot autowire service ".service_locator.vJJ7DQy": it needs an instance of "App\\Entity\\Matchy" but this type has been excluded in "config/services.yaml".'],
        ], [
            'matchy' => 'App\\Entity\\Matchy',
        ]);
    }
}
