<?php

namespace Container0uFQjEc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UQfG62Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UQfG_62' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UQfG_62'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'agent' => ['privates', '.errored..service_locator.UQfG_62.App\\Entity\\Agent', NULL, 'Cannot autowire service ".service_locator.UQfG_62": it needs an instance of "App\\Entity\\Agent" but this type has been excluded in "config/services.yaml".'],
            'questionnaireRepo' => ['privates', 'App\\Repository\\QuestionnaireAgentRepository', 'getQuestionnaireAgentRepositoryService', true],
            'repRepo' => ['privates', 'App\\Repository\\ReponseQuestionnaireRepository', 'getReponseQuestionnaireRepositoryService', true],
        ], [
            'agent' => 'App\\Entity\\Agent',
            'questionnaireRepo' => 'App\\Repository\\QuestionnaireAgentRepository',
            'repRepo' => 'App\\Repository\\ReponseQuestionnaireRepository',
        ]);
    }
}
