<?php

namespace Container0uFQjEc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OHa52deService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oHa52de' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oHa52de'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'questionnaireAgent' => ['privates', '.errored..service_locator.oHa52de.App\\Entity\\QuestionnaireAgent', NULL, 'Cannot autowire service ".service_locator.oHa52de": it needs an instance of "App\\Entity\\QuestionnaireAgent" but this type has been excluded in "config/services.yaml".'],
        ], [
            'questionnaireAgent' => 'App\\Entity\\QuestionnaireAgent',
        ]);
    }
}
