<?php

namespace Container0uFQjEc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getShopItemService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator..7uivSM.App\Entity\ShopItem' shared service.
     *
     * @return \App\Entity\ShopItem
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator..7uivSM": it needs an instance of "App\\Entity\\ShopItem" but this type has been excluded in "config/services.yaml".');
    }
}
