<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ShopItem extends \App\Entity\ShopItem implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'buyerId' => [parent::class, 'buyerId', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'itemCategory' => [parent::class, 'itemCategory', null],
        "\0".parent::class."\0".'itemDescription' => [parent::class, 'itemDescription', null],
        "\0".parent::class."\0".'itemName' => [parent::class, 'itemName', null],
        "\0".parent::class."\0".'payment' => [parent::class, 'payment', null],
        "\0".parent::class."\0".'price' => [parent::class, 'price', null],
        "\0".parent::class."\0".'purchaseDate' => [parent::class, 'purchaseDate', null],
        "\0".parent::class."\0".'quantity' => [parent::class, 'quantity', null],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null],
        "\0".parent::class."\0".'totalPrice' => [parent::class, 'totalPrice', null],
        'buyerId' => [parent::class, 'buyerId', null],
        'id' => [parent::class, 'id', null],
        'itemCategory' => [parent::class, 'itemCategory', null],
        'itemDescription' => [parent::class, 'itemDescription', null],
        'itemName' => [parent::class, 'itemName', null],
        'payment' => [parent::class, 'payment', null],
        'price' => [parent::class, 'price', null],
        'purchaseDate' => [parent::class, 'purchaseDate', null],
        'quantity' => [parent::class, 'quantity', null],
        'status' => [parent::class, 'status', null],
        'totalPrice' => [parent::class, 'totalPrice', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
