<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Agent extends \App\Entity\Agent implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'dateOfCreation' => [parent::class, 'dateOfCreation', null],
        "\0".parent::class."\0".'game' => [parent::class, 'game', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'player' => [parent::class, 'player', null],
        "\0".parent::class."\0".'pseudo' => [parent::class, 'pseudo', null],
        "\0".parent::class."\0".'rank' => [parent::class, 'rank', null],
        "\0".parent::class."\0".'socialsLink' => [parent::class, 'socialsLink', null],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null],
        "\0".parent::class."\0".'team' => [parent::class, 'team', null],
        'dateOfCreation' => [parent::class, 'dateOfCreation', null],
        'game' => [parent::class, 'game', null],
        'id' => [parent::class, 'id', null],
        'player' => [parent::class, 'player', null],
        'pseudo' => [parent::class, 'pseudo', null],
        'rank' => [parent::class, 'rank', null],
        'socialsLink' => [parent::class, 'socialsLink', null],
        'status' => [parent::class, 'status', null],
        'team' => [parent::class, 'team', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
