<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class QuestionnaireAgent extends \App\Entity\QuestionnaireAgent implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'agent' => [parent::class, 'agent', null],
        "\0".parent::class."\0".'game' => [parent::class, 'game', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'ques1' => [parent::class, 'ques1', null],
        "\0".parent::class."\0".'ques2' => [parent::class, 'ques2', null],
        "\0".parent::class."\0".'ques3' => [parent::class, 'ques3', null],
        "\0".parent::class."\0".'ques4' => [parent::class, 'ques4', null],
        'agent' => [parent::class, 'agent', null],
        'game' => [parent::class, 'game', null],
        'id' => [parent::class, 'id', null],
        'ques1' => [parent::class, 'ques1', null],
        'ques2' => [parent::class, 'ques2', null],
        'ques3' => [parent::class, 'ques3', null],
        'ques4' => [parent::class, 'ques4', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
