<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TrainingPlan extends \App\Entity\TrainingPlan implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'coach_id' => [parent::class, 'coach_id', null],
        "\0".parent::class."\0".'coachingSessions' => [parent::class, 'coachingSessions', null],
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'difficulty_level' => [parent::class, 'difficulty_level', null],
        "\0".parent::class."\0".'focus_area' => [parent::class, 'focus_area', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'title' => [parent::class, 'title', null],
        'coach_id' => [parent::class, 'coach_id', null],
        'coachingSessions' => [parent::class, 'coachingSessions', null],
        'created_at' => [parent::class, 'created_at', null],
        'description' => [parent::class, 'description', null],
        'difficulty_level' => [parent::class, 'difficulty_level', null],
        'focus_area' => [parent::class, 'focus_area', null],
        'id' => [parent::class, 'id', null],
        'title' => [parent::class, 'title', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
