<?php

namespace ContainerIAL3q0d;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TsVqtcPService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.TsVqtcP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TsVqtcP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'coachingSession' => ['privates', '.errored..service_locator.TsVqtcP.App\\Entity\\CoachingSession', NULL, 'Cannot autowire service ".service_locator.TsVqtcP": it needs an instance of "App\\Entity\\CoachingSession" but this type has been excluded in "config/services.yaml".'],
        ], [
            'coachingSession' => 'App\\Entity\\CoachingSession',
        ]);
    }
}
