<?php

namespace ContainerIAL3q0d;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7HT4HQ7Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.7HT4HQ7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7HT4HQ7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'trainingPlanRepository' => ['privates', 'App\\Repository\\TrainingPlanRepository', 'getTrainingPlanRepositoryService', true],
        ], [
            'trainingPlanRepository' => 'App\\Repository\\TrainingPlanRepository',
        ]);
    }
}
