<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIAL3q0d\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIAL3q0d/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerIAL3q0d.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerIAL3q0d\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerIAL3q0d\App_KernelProdContainer([
    'container.build_hash' => 'IAL3q0d',
    'container.build_id' => '0876c3ac',
    'container.build_time' => 1770494295,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIAL3q0d');
