<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_back_dashboard' => [[], ['_controller' => 'App\\Controller\\Back\\DashboardController::index'], [], [['text', '/admin/']], [], [], []],
    'app_back_matchy_index' => [[], ['_controller' => 'App\\Controller\\Back\\MatchyController::index'], [], [['text', '/admin/matchy/']], [], [], []],
    'app_back_matchy_new' => [[], ['_controller' => 'App\\Controller\\Back\\MatchyController::new'], [], [['text', '/admin/matchy/new']], [], [], []],
    'app_back_matchy_show' => [['id'], ['_controller' => 'App\\Controller\\Back\\MatchyController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/matchy']], [], [], []],
    'app_back_matchy_edit' => [['id'], ['_controller' => 'App\\Controller\\Back\\MatchyController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/admin/matchy']], [], [], []],
    'app_back_matchy_delete' => [['id'], ['_controller' => 'App\\Controller\\Back\\MatchyController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/matchy']], [], [], []],
    'app_back_team_index' => [[], ['_controller' => 'App\\Controller\\Back\\TeamController::index'], [], [['text', '/admin/team/']], [], [], []],
    'app_back_team_new' => [[], ['_controller' => 'App\\Controller\\Back\\TeamController::new'], [], [['text', '/admin/team/new']], [], [], []],
    'app_back_team_show' => [['id'], ['_controller' => 'App\\Controller\\Back\\TeamController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/team']], [], [], []],
    'app_back_team_edit' => [['id'], ['_controller' => 'App\\Controller\\Back\\TeamController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/admin/team']], [], [], []],
    'app_back_team_delete' => [['id'], ['_controller' => 'App\\Controller\\Back\\TeamController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/team']], [], [], []],
    'app_matchy_index' => [[], ['_controller' => 'App\\Controller\\MatchyController::index'], [], [['text', '/matchy/']], [], [], []],
    'app_matchy_new' => [[], ['_controller' => 'App\\Controller\\MatchyController::new'], [], [['text', '/matchy/new']], [], [], []],
    'app_matchy_show' => [['id'], ['_controller' => 'App\\Controller\\MatchyController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/matchy']], [], [], []],
    'app_matchy_edit' => [['id'], ['_controller' => 'App\\Controller\\MatchyController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/matchy']], [], [], []],
    'app_matchy_delete' => [['id'], ['_controller' => 'App\\Controller\\MatchyController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/matchy']], [], [], []],
    'app_team_index' => [[], ['_controller' => 'App\\Controller\\TeamController::index'], [], [['text', '/team/']], [], [], []],
    'app_team_new' => [[], ['_controller' => 'App\\Controller\\TeamController::new'], [], [['text', '/team/new']], [], [], []],
    'app_team_show' => [['id'], ['_controller' => 'App\\Controller\\TeamController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/team']], [], [], []],
    'app_team_edit' => [['id'], ['_controller' => 'App\\Controller\\TeamController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/team']], [], [], []],
    'app_team_delete' => [['id'], ['_controller' => 'App\\Controller\\TeamController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/team']], [], [], []],
];
