<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0uFQjEc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0uFQjEc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0uFQjEc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0uFQjEc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0uFQjEc\App_KernelDevDebugContainer([
    'container.build_hash' => '0uFQjEc',
    'container.build_id' => 'b72263d7',
    'container.build_time' => 1770694651,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0uFQjEc');
