<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS5T8cPd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS5T8cPd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerS5T8cPd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerS5T8cPd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerS5T8cPd\App_KernelDevDebugContainer([
    'container.build_hash' => 'S5T8cPd',
    'container.build_id' => '4397f24f',
    'container.build_time' => 1771774873,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerS5T8cPd');
