<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIiPvv3u\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIiPvv3u/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIiPvv3u.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIiPvv3u\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIiPvv3u\App_KernelDevDebugContainer([
    'container.build_hash' => 'IiPvv3u',
    'container.build_id' => 'f39d3656',
    'container.build_time' => 1770928910,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIiPvv3u');
