<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRLjGULG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRLjGULG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRLjGULG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRLjGULG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRLjGULG\App_KernelDevDebugContainer([
    'container.build_hash' => 'RLjGULG',
    'container.build_id' => '951cda1f',
    'container.build_time' => 1771321279,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRLjGULG');
