<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Matchy extends \App\Entity\Matchy implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'game' => [parent::class, 'game', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'match_date' => [parent::class, 'match_date', null],
        "\0".parent::class."\0".'score_team1' => [parent::class, 'score_team1', null],
        "\0".parent::class."\0".'score_team2' => [parent::class, 'score_team2', null],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null],
        "\0".parent::class."\0".'team1' => [parent::class, 'team1', null],
        "\0".parent::class."\0".'team2' => [parent::class, 'team2', null],
        "\0".parent::class."\0".'winner_team' => [parent::class, 'winner_team', null],
        'game' => [parent::class, 'game', null],
        'id' => [parent::class, 'id', null],
        'match_date' => [parent::class, 'match_date', null],
        'score_team1' => [parent::class, 'score_team1', null],
        'score_team2' => [parent::class, 'score_team2', null],
        'status' => [parent::class, 'status', null],
        'team1' => [parent::class, 'team1', null],
        'team2' => [parent::class, 'team2', null],
        'winner_team' => [parent::class, 'winner_team', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
